title: ericwen229's blog
email: eericwen@icloud.com
description: "Hey! It's ericwen229 over here."
url: "https://ericwen229.github.io"
baseurl: ""
github_username: ericwen229
lang: zh-CN
timezone: Asia/Shanghai

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - archive/
  - README.md
  - Gemfile
  - Gemfile.lock
  - .bundle/
  - vendor/
